### ISSUE TITLE
v3.0 update

### ISSUE THREAD

**Issue by niizam** [VHSgunzo/gi_patch#1]
PR from [zeroday0619](https://github.com/legluondunet/MyLittleLutrisScripts/pull/131)

**Comment by VHSgunzo** [comment]
Patch updated:

https://github.com/VHSgunzo/gi_patch/releases/tag/v2.8

https://github.com/VHSgunzo/lutris-wine/releases/tag/v0.74

**Comment by VHSgunzo** [comment]
this patch is not from zeroday0619

**Comment by niizam** [comment]
v3.0 update
thank you
